flags: {}
packages:
- '.'
- location:
    git: https://github.com/robstewart57/bindings-dc1394.git
    commit: f0859dcdd414bfef95c1db242495cce320fc77b4
- location:
    git: https://github.com/aleator/CV.git
    commit: 1e2c9116bcaacdf305044c861a1b36d0d8fb71b7
extra-deps:
- accelerate-cuda-0.15.1.1
- accelerate-io-0.15.1.0
- cuda-0.7.5.2
- lazysmallcheck-0.6
- storable-record-0.0.3.1
- storable-tuple-0.0.3.2
resolver: lts-6.30
